<a href="https://colab.research.google.com/github/saheedniyi02/fpl-ai/blob/master/clean_fixtures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
seasons=["2020-21","2021-22","2022-23"]
unused_columns=["xP","opponent_team","expected_assists","expected_goal_involvements","expected_goals",
                "expected_goals_conceded","element_type_ex","team_h_score","team_a_score","element" , "round" ,"fixture","starts" ]
#stats that you want to use their values for the last few games to predict a

no_last_stats=3 #number of last gameweek stats to use for prediction

history_stats=["assists","bonus","bps","clean_sheets","creativity","goals_conceded","goals_scored","ict_index","influence","minutes",
               "own_goals","penalties_missed","penalties_saved","red_cards","saves","selected","threat","total_points","transfers_in","transfers_out","value","match_result","team Goal scored","team Goal conceded"]

last_features=[f"last {no_last_stats} {stat}" for stat in history_stats]

mean_features=["assists","bonus","bps","clean_sheets","creativity","goals_conceded",
     "goals_scored","ict_index","influence","minutes"
     ,"own_goals","penalties_missed","penalties_saved",
     "red_cards","saves","selected","threat","total_points"
     ,"transfers_in","transfers_out","value","match_result","team Goal scored","team Goal conceded"]

std_features=["bps","creativity","ict_index","influence","minutes","selected","threat","total_points","transfers_in","transfers_out","value"]



dropped_columns = [
    "season",
    "opponent",
    "match_result",
    "position",
    "assists",
    "penalties_missed",
    "bonus",
    "bps",
    "clean_sheets",
    "creativity",
    "goals_conceded",
    "goals_scored",
    "ict_index",
    "influence",
    "own_goals",
    "penalties_saved",
    "red_cards",
    "saves",
    "selected",
    "threat",
    "transfers_balance",
    "transfers_in",
    "transfers_out",
    "yellow_cards"
]  # "value",



leak_columns = [
    "name",
    "team",
]  # columns that shouldnt be used in training fir fear of data leakage



short_term_stats=3

team_features=["team Goal scored","team Goal conceded"]

In [ ]:
#from config import *
import numpy as np
import pandas as pd
from scipy import stats


def split_test(data, gameweek):
    # print(data["GW"].value_counts())
    data_gw = data[data["GW"] == gameweek]
    data_other_gw = data[~(data["GW"] == gameweek)]
    return data_gw, data_other_gw


def check_win(df):
    list_win = []
    for index in df.index:
        result = (df["team_a_score"] - df["team_h_score"]).loc[index]
        is_home = df["was_home"].loc[index]
        if result == 0:
            list_win.append(1)
        elif result > 0 and is_home == True:
            list_win.append(0)
        elif result < 0 and is_home == True:
            list_win.append(3)
        elif result > 0 and is_home == False:
            list_win.append(3)
        elif result < 0 and is_home == False:
            list_win.append(0)
        else:
            list_win.append(-1)
    return list_win


def get_2020_21_season_pos(club):
    """get the position of the club in the 2020-21 season"""
    if club == "Man City":
        return 1
    elif club == "Man Utd":
        return 2
    elif club == "Liverpool":
        return 3
    elif club == "Chelsea":
        return 4
    elif club == "Leicester":
        return 5
    elif club == "West Ham":
        return 6
    elif club == "Spurs":
        return 7
    elif club == "Arsenal":
        return 8
    elif club == "Leeds":
        return 9
    elif club == "Everton":
        return 10
    elif club == "Aston Villa":
        return 11
    elif club == "Newcastle":
        return 12
    elif club == "Wolves":
        return 13
    elif club == "Crystal Palace":
        return 14
    elif club == "Southampton":
        return 15
    elif club == "Brighton":
        return 16
    elif club == "Burnley":
        return 17
    else:
        return 20


def get_2019_20_season_pos(club):
    """get the position of the club in the 2019-20 season"""
    if club == "Liverpool":
        return 1
    elif club == "Man City":
        return 2
    elif club == "Man Utd":
        return 3
    elif club == "Chelsea":
        return 4
    elif club == "Leicester":
        return 5
    elif club == "Spurs":
        return 6
    elif club == "Wolves":
        return 7
    elif club == "Arsenal":
        return 8
    elif club == "Sheffield Utd":
        return 9
    elif club == "Burnley":
        return 10
    elif club == "Southampton":
        return 11
    elif club == "Everton":
        return 12
    elif club == "Newcastle":
        return 13
    elif club == "Crystal Palace":
        return 14
    elif club == "Brighton":
        return 15
    elif club == "West Ham":
        return 16
    elif club == "Aston Villa":
        return 17
    else:
        return 20


def get_2021_22_season_pos(club):
    if club == "Man City":
        return 1
    elif club == "Liverpool":
        return 2
    elif club == "Chelsea":
        return 3
    elif club == "Spurs":
        return 4
    elif club == "Arsenal":
        return 5
    elif club == "Man Utd":
        return 6
    elif club == "West Ham":
        return 7
    elif club == "Leicester":
        return 8
    elif club == "Brighton":
        return 9
    elif club == "Wolves":
        return 10
    elif club == "Newcastle":
        return 11
    elif club == "Crystal Palace":
        return 12
    elif club == "Brentford":
        return 13
    elif club == "Aston Villa":
        return 14
    elif club == "Southampton":
        return 15
    elif club == "Everton":
        return 16
    elif club == "Leeds":
        return 17
    else:
        return 20


def get_2022_23_season_pos(club):
    if club == "Man City":
        return 1
    elif club == "Arsenal":
        return 2
    elif club == "Man Utd":
        return 3
    elif club == "Newcastle":
        return 4
    elif club == "Liverpool":
        return 5
    elif club == "Brighton":
        return 6
    elif club == "Aston Villa":
        return 7
    elif club == "Spurs":
        return 8
    elif club == "Brentford":
        return 9
    elif club == "Fulham":
        return 10
    elif club == "Crystal Palace":
        return 11
    elif club == "Chelsea":
        return 12
    elif club == "Wolves":
        return 13
    elif club == "West Ham":
        return 14
    elif club == "Bournemouth":
        return 15
    elif club == "Nott'm Forest":
        return 16
    elif club == "Everton":
        return 17
    else:
        return 20


def get_last_season_pos(year):
    """get the function to get the last season position of a team at any year"""
    if year == "2020-21":
        return get_2019_20_season_pos
    elif year == "2021-22":
        return get_2020_21_season_pos
    elif year == "2022-23":
        return get_2021_22_season_pos
    elif year == "2023-24":
        return get_2022_23_season_pos


def remove_neg(val):
    if val > 0:
        return val
    else:
        return -val


def deque_and_queue(stats, value):
    # if -1 in stats:
    #  return stats
    # deque
    stats = stats[1:]
    stats.append(value)
    return stats


def get_last_stats(data, stat, name, no_last_stats=3):
    name_df = data[data["name"] == name]
    seasons = ["2020-21", "2021-22", "2022-23"]
    name_df_dict = {}
    for season in seasons:
        name_df_season = name_df[name_df["season"] == season]
        list_stats = []
        stats_x = []
        for value in name_df_season[stat]:
            if len(stats_x) < no_last_stats:
                list_stats.append(np.array(stats_x))
                stats_x.append(value)
            else:
                list_stats.append(np.array(stats_x))
                stats_x = deque_and_queue(stats_x, value)
        name_df_season[f"last {no_last_stats} {stat}"] = list_stats
        name_df_dict[season] = name_df_season
    return pd.concat(name_df_dict.values())


def get_all_players_last_stats(data, stat, no_last_stats=3):
    players_df = []
    for player in data["name"].unique():
        data_player = get_last_stats(data, stat, player, no_last_stats)
        players_df.append(data_player)
    # print(pd.concat(players_df))
    return pd.concat(players_df)


def get_last_stats_test(data, stat, name, no_last_stats=3):
    name_df = data[data["name"] == name]
    list_stats = []
    stats_x = []
    for value in name_df[stat]:
        if len(stats_x) < no_last_stats:
            list_stats.append(np.array(stats_x))
            stats_x.append(value)
        else:
            list_stats.append(np.array(stats_x))
            stats_x = deque_and_queue(stats_x, value)
    name_df[f"last {no_last_stats} {stat}"] = list_stats
    return name_df


def get_players_last_stats_test(data, stat, no_last_stats=short_term_stats):
    players_df = []
    for player in data["name"].unique():
        data_player = get_last_stats_test(data, stat, player, no_last_stats)
        players_df.append(data_player)
    # print(pd.concat(players_df))
    return pd.concat(players_df)

def get_all_stats_test(data, stat, name):
    name_df = data[data["name"] == name]
    list_stats = []
    stats_x = []
    for value in name_df[stat]:
        list_stats.append(np.array(stats_x))
        stats_x.append(value)
    name_df[f"all {stat}"] = list_stats
    return name_df


def get_players_all_stats_test(data, stat):
    players_df = []
    for player in data["name"].unique():
        data_player = get_all_stats_test(data, stat, player)
        players_df.append(data_player)
    # print(pd.concat(players_df))
    return pd.concat(players_df)

def convert_minutes(val):
    """CONVERTS MINUTES TO A CATEGORICAL OUTPUT"""
    if val > 10:
        return 1
    else:
        return 0


def find_mode(vals):
    """find the mode of vals"""
    try:
        if -1 in vals:
            return -1
        return stats.mode(vals)[0][0]
    except IndexError:
        return np.nan


def find_mean(vals):
    """find the mean of vals"""
    try:
        if -1 in vals:
            return -1
        return np.mean(vals)
    except:
        return np.nan


def find_max(vals):
    """find the maximum of vals"""
    try:
        if -1 in vals:
            return -1
        return np.max(vals)
    except:
        return np.nan


def find_std(vals):
    """find the standard deviation of vals"""
    try:
        if -1 in vals:
            return -1
        return np.std(vals)
    except:
        return np.nan


def find_value_count(vals, to_count):
    """find the number of times to_count appears in vals"""
    try:
        if -1 in vals:
            return -1
        values, count = np.unique(vals, return_counts=True)
        index = np.where(values == to_count)[0][0]
        return count[index]

    except:
        return -2


def get_opp_team(data):
    """get the opponent team for each player"""
    opp_teams = []
    home_teams = data["home_team"]
    away_teams = data["away_team"]
    my_teams = data["team"]
    for id in data.index:
        my_team = my_teams.iloc[id]
        home_team = home_teams.iloc[id]
        away_team = away_teams.iloc[id]
        if my_team == home_team:
            opp_teams.append(away_team)
        else:
            opp_teams.append(home_team)
    return opp_teams




def create_features(data, mean_features, std_features):
    for mean_feature in mean_features:
        print(mean_feature)
        data[f"mean {mean_feature} {no_last_stats}"] = [
            find_mean(values) for values in data[f"last {no_last_stats} {mean_feature}"]
        ]
        data[f"mean {mean_feature} all"] = [
            find_mean(values) for values in data[f"all {mean_feature}"]
        ]
        #data[f"mean {mean_feature} all"]= data[f"mean {mean_feature} all"]/data["GW"]
    for std_feature in std_features:
        print(std_feature)
        data[f"std {std_feature} {no_last_stats}"] = [
            find_std(values) for values in data[f"last {no_last_stats} {std_feature}"]
        ]
    return data

In [ ]:


import pandas as pd
import numpy as np
#from config import unused_columns, history_stats, no_last_stats
import warnings

warnings.filterwarnings("ignore")


def calculate_ratio_team_value(name, df=None):
    """Calculate the ratio of player value to team value"""
    team = df[df["name"] == name]["team"].iloc[0]
    total_value = df[df["team"] == team]["value"].sum()
    value = df[df["name"] == name]["value"].iloc[0]
    return value * 100 / total_value


def calculate_position_rank(name, df=None):
    """Calculate the number of players with a higher  value"""
    value = df[df["name"] == name]["value"].iloc[0]
    position = df[df["name"] == name]["position"].iloc[0]
    team = df[df["name"] == name]["team"].iloc[0]
    return df[
        (df["value"] > value) & (df["position"] == position) & (df["team"] == team)
    ]["value"].shape[0]


gameweek = 10
old_gameweek_results = []
for i in range(1, gameweek):
    result = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /datasets/2023-24/results/GW{i}.csv", index_col=0)
    result.columns = [
        "element",
        "fixture",
        "opponent_team",
        "total_points",
        "was_home",
        "kickoff_time",
        "team_h_score",
        "team_a_score",
        "round",
        "minutes",
        "goals_scored",
        "assists",
        "clean_sheets",
        "goals_conceded",
        "own_goals",
        "penalties_saved",
        "penalties_missed",
        "yellow_cards",
        "red_cards",
        "saves",
        "bonus",
        "bps",
        "influence",
        "creativity",
        "threat",
        "ict_index",
        "starts",
        "expected_goals",
        "expected_assists",
        "expected_goal_involvements",
        "expected_goals_conceded",
        "value",
        "transfers_balance",
        "selected",
        "transfers_in",
        "transfers_out",
        "id",
        "name",
        "cost",
        "position",
        "home_team",
        "away_team",
        "team",
    ]
    year = "2023-24"
    previous_year = "2022-23"
    result["xP"] = 0
    result["GW"] = i
    result["match_result"] = check_win(result)
    result["opponent"] = get_opp_team(result)
    print(result.shape)
    result["last_season_position"] = result["team"].apply(get_last_season_pos(year))
    result["opponent_last_season_position"] = result["opponent"].apply(
        get_last_season_pos(year)
    )
    result["percent_value"] = result["name"].apply(
        calculate_ratio_team_value, args=(result,)
    )
    result["position rank"] = result["name"].apply(
        calculate_position_rank, args=(result,)
    )

    player_prev_stats = pd.read_csv(
        f"https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/{previous_year}/cleaned_players.csv"
    )
    player_prev_stats["name"] = (
        player_prev_stats["first_name"] + " " + player_prev_stats["second_name"]
    )
    player_prev_stats.drop(["first_name", "second_name"], axis=1, inplace=True)
    player_prev_stats.columns = player_prev_stats.columns + "_ex"
    result = pd.merge(
        result, player_prev_stats, left_on="name", right_on="name_ex", how="left"
    )
    result_home=result[result["was_home"]==True]
    result_away=result[result["was_home"]==False]
    result_home["team Goal scored"]=result_home["team_h_score"]
    result_home["team Goal conceded"]=result_home["team_a_score"]
    result_away["team Goal conceded"]=result_away["team_h_score"]
    result_away["team Goal scored"]=result_away["team_a_score"]
    result=pd.concat([result_home,result_away])
    result.drop(unused_columns, axis=1, inplace=True)
    old_gameweek_results.append(result)
    print(i)

# print(old_gameweek_results[0]["opponent"].value_counts())
current_fixture = pd.read_csv(
    f"/content/drive/MyDrive/Fplpredict /datasets/2023-24/fixtures/GW{gameweek}.csv", index_col=0
)
current_fixture.columns = [
    "id",
    "name",
    "value",
    "position",
    "home_team",
    "away_team",
    "kickoff_time",
    "was_home",
    "team",
]


current_fixture["opponent"] = get_opp_team(current_fixture)
# print(current_fixture["opponent"].value_counts())
current_fixture["last_season_position"] = current_fixture["team"].apply(
    get_last_season_pos(year)
)
current_fixture["opponent_last_season_position"] = current_fixture["opponent"].apply(
    get_last_season_pos(year)
)
current_fixture["percent_value"] = current_fixture["name"].apply(
    calculate_ratio_team_value, args=(current_fixture,)
)
current_fixture["position rank"] = current_fixture["name"].apply(
    calculate_position_rank, args=(current_fixture,)
)


# check_win not posible because it's only fixtures we have for now
# merge last season data
player_prev_stats = pd.read_csv(
    f"https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/{previous_year}/cleaned_players.csv"
)

player_prev_stats["name"] = (
    player_prev_stats["first_name"] + " " + player_prev_stats["second_name"]
)

player_prev_stats.drop(["first_name", "second_name"], axis=1, inplace=True)
player_prev_stats.columns = player_prev_stats.columns + "_ex"
current_fixture = pd.merge(
    current_fixture, player_prev_stats, left_on="name", right_on="name_ex", how="left"
)

current_fixture["GW"] = gameweek
old_gameweek_results.append(current_fixture)
data = pd.concat(old_gameweek_results)

data = data.sort_values(["name", "kickoff_time"], ascending=True)


data["season"] = year
data.drop(["name_ex", "id", "home_team", "away_team"], axis=1, inplace=True)

for stat in history_stats:
    print(stat)
    data = get_players_last_stats_test(data, stat)
    data = get_players_all_stats_test(data, stat)

data = create_features(data, mean_features, std_features)
data.drop(
    [f"last {no_last_stats} {stat}" for stat in history_stats], axis=1, inplace=True
)
data.drop([f"all {stat}" for stat in history_stats],axis=1,inplace=True)
data["ratio_goal_scored 3"]=((data["mean goals_scored 3"]/data["mean team Goal scored 3"]).replace(np.inf, 0))*100
data["ratio_goal_scored all"]=((data["mean goals_scored all"]/data["mean team Goal scored all"]).replace(np.inf, 0))*100

(613, 47)
1
(585, 47)
2
(405, 47)
3
(584, 47)
4
(585, 47)
5
(585, 47)
6
(658, 47)
7
(658, 47)
8
(658, 47)
9
assists
bonus
bps
clean_sheets
creativity
goals_conceded
goals_scored
ict_index
influence
minutes
own_goals
penalties_missed
penalties_saved
red_cards
saves
selected
threat
total_points
transfers_in
transfers_out
value
match_result
team Goal scored
team Goal conceded
assists
bonus
bps
clean_sheets
creativity
goals_conceded
goals_scored
ict_index
influence
minutes
own_goals
penalties_missed
penalties_saved
red_cards
saves
selected
threat
total_points
transfers_in
transfers_out
value
match_result
team Goal scored
team Goal conceded
bps
creativity
ict_index
influence
minutes
selected
threat
total_points
transfers_in
transfers_out
value

In [ ]:
#add opponent stats for gameweeks
list_data_gw=[]
for GW in range(1,gameweek + 1):

    data_gw=data[data["GW"]==GW].sort_values(by="mean team Goal scored all", ascending=False)
    data_opponent=data_gw.drop_duplicates(subset="team")[['team','mean team Goal scored 3','mean team Goal conceded 3','mean team Goal scored all','mean team Goal conceded all',"mean match_result all"]]
    print(data_opponent.reset_index().drop("index",axis=1))
    #print(data_gw.shape)
    data_opponent.columns=['opponent','opp mean team Goal scored 3','opp mean team Goal conceded 3','opp mean team Goal scored all','opp mean team Goal conceded all',"opp mean match_result all"]
    #print(data_opponent.shape)
    data_gw=pd.merge(data_gw,data_opponent,on="opponent",how="left")
    list_data_gw.append(data_gw)

              team  mean team Goal scored 3  mean team Goal conceded 3  \
0            Spurs                      2.0                        2.0
1         Brighton                      NaN                        NaN
2         West Ham                      NaN                        NaN
3        Brentford                      NaN                        NaN
4          Arsenal                      NaN                        NaN
5          Man Utd                      NaN                        NaN
6          Everton                      NaN                        NaN
7          Chelsea                      NaN                        NaN
8    Sheffield Utd                      NaN                        NaN
9      Bournemouth                      NaN                        NaN
10           Luton                      NaN                        NaN
11       Liverpool                      NaN                        NaN
12          Fulham                      NaN                        NaN
13   Nott'm Forest                      NaN                        NaN
14       Newcastle                      NaN                        NaN
15     Aston Villa                      NaN                        NaN
16         Burnley                      NaN                        NaN
17        Man City                      NaN                        NaN
18          Wolves                      NaN                        NaN
19  Crystal Palace                      NaN                        NaN

    mean team Goal scored all  mean team Goal conceded all  \
0                         2.0                          2.0
1                         NaN                          NaN
2                         NaN                          NaN
3                         NaN                          NaN
4                         NaN                          NaN
5                         NaN                          NaN
6                         NaN                          NaN
7                         NaN                          NaN
8                         NaN                          NaN
9                         NaN                          NaN
10                        NaN                          NaN
11                        NaN                          NaN
12                        NaN                          NaN
13                        NaN                          NaN
14                        NaN                          NaN
15                        NaN                          NaN
16                        NaN                          NaN
17                        NaN                          NaN
18                        NaN                          NaN
19                        NaN                          NaN

    mean match_result all
0                     1.0
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN
18                    NaN
19                    NaN
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0        Newcastle                      5.0                        1.0
1         Brighton                      4.0                        1.0
2          Chelsea                      4.0                        1.0
3         Man City                      3.0                        0.0
4          Arsenal                      2.0                        1.0
5        Brentford                      2.0                        2.0
6            Spurs                      2.0                        2.0
7      Aston Villa                      1.0                        5.0
8      Bournemouth                      1.0                        1.0
9    Nott'm Forest                      1.0                        2.0
10         Man Utd                      1.0                        0.0
11  Crystal Palace                      1.0                        0.0
12          Fulham                      1.0                        0.0
13        West Ham                      1.0                        1.0
14       Liverpool                      1.0                        1.0
15          Wolves                      0.0                        1.0
16         Everton                      0.0                        1.0
17   Sheffield Utd                      0.0                        1.0

    mean team Goal scored all  mean team Goal conceded all  \
0                         5.0                          1.0
1                         4.0                          1.0
2                         4.0                          1.0
3                         3.0                          0.0
4                         2.0                          1.0
5                         2.0                          2.0
6                         2.0                          2.0
7                         1.0                          5.0
8                         1.0                          1.0
9                         1.0                          2.0
10                        1.0                          0.0
11                        1.0                          0.0
12                        1.0                          0.0
13                        1.0                          1.0
14                        1.0                          1.0
15                        0.0                          1.0
16                        0.0                          1.0
17                        0.0                          1.0

    mean match_result all
0                     3.0
1                     3.0
2                     3.0
3                     3.0
4                     3.0
5                     1.0
6                     1.0
7                     0.0
8                     1.0
9                     0.0
10                    3.0
11                    3.0
12                    3.0
13                    1.0
14                    1.0
15                    0.0
16                    0.0
17                    0.0
             team  mean team Goal scored 3  mean team Goal conceded 3  \
0        Brighton                      4.0                        1.0
1     Aston Villa                      4.0                        0.0
2       Brentford                      3.0                        0.0
3       Newcastle                      2.5                        1.0
4         Chelsea                      2.5                        2.0
5   Nott'm Forest                      2.0                        1.0
6           Spurs                      2.0                        1.0
7        Man City                      2.0                        0.0
8          Wolves                      2.0                        0.0
9         Man Utd                      2.0                        1.0
10        Arsenal                      1.5                        0.5
11    Bournemouth                      1.0                        2.0
12  Sheffield Utd                      1.0                        2.0
13        Burnley                      0.0                        3.0

    mean team Goal scored all  mean team Goal conceded all  \
0                         4.0                          1.0
1                         4.0                          0.0
2                         3.0                          0.0
3                         2.5                          1.0
4                         2.5                          2.0
5                         2.0                          1.0
6                         2.0                          1.0
7                         2.0                          0.0
8                         2.0                          0.0
9                         2.0                          1.0
10                        1.5                          0.5
11                        1.0                          2.0
12                        1.0                          2.0
13                        0.0                          3.0

    mean match_result all
0                     3.0
1                     3.0
2                     3.0
3                     1.5
4                     1.5
5                     3.0
6                     2.0
7                     3.0
8                     3.0
9                     2.0
10                    3.0
11                    0.5
12                    0.0
13                    0.0
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0         Brighton                 4.000000                   1.000000
1      Aston Villa                 3.500000                   0.500000
2        Liverpool                 3.000000                   1.000000
3         West Ham                 3.000000                   1.000000
4          Chelsea                 2.666667                   1.333333
5        Newcastle                 2.500000                   1.000000
6    Sheffield Utd                 2.500000                   2.500000
7            Spurs                 3.000000                   0.666667
8         Man City                 2.000000                   0.333333
9        Brentford                 2.000000                   1.000000
10   Nott'm Forest                 2.000000                   2.000000
11         Man Utd                 2.000000                   0.666667
12          Wolves                 2.000000                   0.333333
13         Arsenal                 1.666667                   1.000000
14  Crystal Palace                 1.666667                   1.000000
15           Luton                 1.666667                   1.000000
16     Bournemouth                 0.666667                   2.000000
17          Fulham                 0.500000                   1.500000
18         Everton                 0.000000                   2.500000

    mean team Goal scored all  mean team Goal conceded all  \
0                    4.000000                     1.000000
1                    3.500000                     0.500000
2                    3.000000                     1.000000
3                    3.000000                     1.000000
4                    2.666667                     1.333333
5                    2.500000                     1.000000
6                    2.500000                     2.500000
7                    2.428571                     0.857143
8                    2.000000                     0.333333
9                    2.000000                     1.000000
10                   2.000000                     2.000000
11                   2.000000                     0.666667
12                   2.000000                     0.333333
13                   1.666667                     1.000000
14                   1.666667                     1.000000
15                   1.666667                     1.000000
16                   0.666667                     2.000000
17                   0.500000                     1.500000
18                   0.000000                     2.500000

    mean match_result all
0                3.000000
1                3.000000
2                3.000000
3                3.000000
4                2.000000
5                1.500000
6                1.500000
7                2.428571
8                3.000000
9                1.666667
10               1.500000
11               2.333333
12               3.000000
13               2.333333
14               2.333333
15               2.333333
16               0.333333
17               1.500000
18               0.000000
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0         Brighton                 3.666667                   1.000000
1            Spurs                 3.500000                   1.000000
2        Liverpool                 3.000000                   0.500000
3         Man City                 3.000000                   0.333333
4    Sheffield Utd                 3.000000                   0.333333
5         West Ham                 2.500000                   1.000000
6      Aston Villa                 2.333333                   1.333333
7   Crystal Palace                 2.000000                   1.000000
8        Brentford                 2.000000                   1.000000
9          Arsenal                 2.000000                   1.000000
10          Wolves                 1.666667                   1.333333
11           Luton                 2.000000                   1.000000
12       Newcastle                 2.000000                   1.666667
13         Chelsea                 1.333333                   1.333333
14         Man Utd                 1.666667                   1.000000
15   Nott'm Forest                 1.666667                   1.333333
16     Bournemouth                 1.000000                   2.333333
17         Everton                 1.000000                   3.000000
18          Fulham                 0.666667                   2.666667

    mean team Goal scored all  mean team Goal conceded all  \
0                    3.666667                     1.000000
1                    3.500000                     1.000000
2                    3.000000                     0.500000
3                    3.000000                     0.333333
4                    3.000000                     0.333333
5                    2.500000                     1.000000
6                    2.333333                     1.333333
7                    2.000000                     1.000000
8                    2.000000                     1.250000
9                    2.000000                     1.000000
10                   2.000000                     1.000000
11                   2.000000                     1.000000
12                   2.000000                     1.666667
13                   2.000000                     1.250000
14                   1.750000                     1.250000
15                   1.666667                     1.333333
16                   1.000000                     2.000000
17                   1.000000                     3.000000
18                   0.666667                     2.666667

    mean match_result all
0                    3.00
1                    3.00
2                    3.00
3                    3.00
4                    3.00
5                    3.00
6                    2.00
7                    2.50
8                    1.50
9                    2.50
10                   2.25
11                   2.50
12                   1.00
13                   1.50
14                   1.75
15                   2.00
16                   0.50
17                   0.50
18                   1.00
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0         Brighton                 3.333333                   1.000000
1         Man City                 3.000000                   0.666667
2            Spurs                 3.000000                   1.000000
3        Liverpool                 3.000000                   0.666667
4      Aston Villa                 2.000000                   1.666667
5    Sheffield Utd                 2.333333                   1.000000
6         West Ham                 2.000000                   1.666667
7          Arsenal                 2.000000                   1.000000
8           Wolves                 1.666667                   2.333333
9   Crystal Palace                 2.000000                   2.000000
10       Newcastle                 0.666667                   1.333333
11       Brentford                 1.000000                   1.333333
12         Chelsea                 1.000000                   0.333333
13           Luton                 1.666667                   1.333333
14         Man Utd                 1.333333                   2.000000
15   Nott'm Forest                 1.333333                   1.333333
16     Bournemouth                 0.666667                   1.333333
17          Fulham                 0.666667                   2.666667
18         Everton                 0.666667                   2.333333

    mean team Goal scored all  mean team Goal conceded all  \
0                    3.500000                     1.000000
1                    3.000000                     0.500000
2                    3.000000                     1.000000
3                    3.000000                     0.666667
4                    2.500000                     1.250000
5                    2.500000                     0.750000
6                    2.000000                     1.666667
7                    1.800000                     0.800000
8                    1.800000                     1.400000
9                    1.800000                     1.400000
10                   1.750000                     1.250000
11                   1.600000                     1.200000
12                   1.600000                     1.000000
13                   1.600000                     1.000000
14                   1.600000                     1.600000
15                   1.500000                     1.250000
16                   0.800000                     1.600000
17                   0.750000                     2.000000
18                   0.666667                     2.333333

    mean match_result all
0                3.000000
1                3.000000
2                3.000000
3                3.000000
4                2.250000
5                2.250000
6                2.000000
7                2.600000
8                1.800000
9                2.000000
10               1.500000
11               1.200000
12               1.400000
13               2.000000
14               1.400000
15               1.750000
16               0.600000
17               1.500000
18               0.333333
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0         Brighton                 3.000000                   1.000000
1        Newcastle                 3.333333                   1.000000
2        Liverpool                 3.000000                   0.666667
3         Man City                 3.333333                   0.666667
4            Spurs                 3.000000                   1.666667
5      Aston Villa                 1.333333                   1.333333
6    Sheffield Utd                 2.000000                   3.666667
7          Burnley                 2.000000                   5.000000
8          Arsenal                 2.000000                   1.000000
9         West Ham                 1.333333                   2.333333
10          Wolves                 1.333333                   2.333333
11       Brentford                 1.000000                   2.000000
12  Crystal Palace                 1.333333                   1.333333
13           Luton                 1.333333                   1.000000
14         Man Utd                 1.000000                   2.000000
15         Chelsea                 0.000000                   0.666667
16         Everton                 1.666667                   1.333333
17   Nott'm Forest                 0.666667                   1.000000
18     Bournemouth                 1.000000                   1.666667
19          Fulham                 0.666667                   1.666667

    mean team Goal scored all  mean team Goal conceded all  \
0                    3.400000                     1.000000
1                    3.000000                     1.000000
2                    3.000000                     0.750000
3                    2.800000                     0.400000
4                    2.750000                     1.250000
5                    2.200000                     1.000000
6                    2.000000                     2.200000

In [ ]:
data=pd.concat(list_data_gw)
data=data.drop_duplicates(["GW","team","opponent","name","kickoff_time"])

In [ ]:
data.shape

(6061, 122)

In [ ]:
5398+509

5907

In [ ]:
data.shape

(6061, 122)

In [ ]:
# save cleaned files
for i in range(1, gameweek + 1):
    data_gw = data[data["GW"] == i]
    data_gw.to_csv(f"/content/drive/MyDrive/Fplpredict /cleaned_dataset/2023-24/GW{i}.csv")
    print(i)

1
2
3
4
5
6
7
8
9
10

# DEBUGGING ERRORS

In [ ]:
list(data.columns)

['total_points',
 'was_home',
 'kickoff_time',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'value',
 'transfers_balance',
 'selected',
 'transfers_in',
 'transfers_out',
 'name',
 'cost',
 'position',
 'team',
 'GW',
 'match_result',
 'opponent',
 'last_season_position',
 'opponent_last_season_position',
 'percent_value',
 'position rank',
 'goals_scored_ex',
 'assists_ex',
 'total_points_ex',
 'minutes_ex',
 'goals_conceded_ex',
 'creativity_ex',
 'influence_ex',
 'threat_ex',
 'bonus_ex',
 'bps_ex',
 'ict_index_ex',
 'clean_sheets_ex',
 'red_cards_ex',
 'yellow_cards_ex',
 'selected_by_percent_ex',
 'now_cost_ex',
 'team Goal scored',
 'team Goal conceded',
 'element_type_ex',
 'season',
 'mean assists 3',
 'mean assists all',
 'mean bonus 3',
 'mean bonus all',
 'mean bps 3',
 'mean bps all',
 'mean clean_sheets 3',
 'mean clean_sheets all',
 'mean creativity 3',
 'mean creativity all',
 'mean goals_conceded 3',
 'mean goals_conceded all',
 'mean goals_scored 3',
 'mean goals_scored all',
 'mean ict_index 3',
 'mean ict_index all',
 'mean influence 3',
 'mean influence all',
 'mean minutes 3',
 'mean minutes all',
 'mean own_goals 3',
 'mean own_goals all',
 'mean penalties_missed 3',
 'mean penalties_missed all',
 'mean penalties_saved 3',
 'mean penalties_saved all',
 'mean red_cards 3',
 'mean red_cards all',
 'mean saves 3',
 'mean saves all',
 'mean selected 3',
 'mean selected all',
 'mean threat 3',
 'mean threat all',
 'mean total_points 3',
 'mean total_points all',
 'mean transfers_in 3',
 'mean transfers_in all',
 'mean transfers_out 3',
 'mean transfers_out all',
 'mean value 3',
 'mean value all',
 'mean match_result 3',
 'mean match_result all',
 'mean team Goal scored 3',
 'mean team Goal scored all',
 'mean team Goal conceded 3',
 'mean team Goal conceded all',
 'std bps 3',
 'std creativity 3',
 'std ict_index 3',
 'std influence 3',
 'std minutes 3',
 'std selected 3',
 'std threat 3',
 'std total_points 3',
 'std transfers_in 3',
 'std transfers_out 3',
 'std value 3',
 'ratio_goal_scored 3',
 'ratio_goal_scored all',
 'opp mean team Goal scored 3',
 'opp mean team Goal conceded 3',
 'opp mean team Goal scored all',
 'opp mean team Goal conceded all',
 'opp mean match_result all']

In [ ]:
for GW in range(1,gameweek + 1):
  print(f"GW{GW}")
  print(data[data["GW"]==GW]["team"].shape)

GW1
(613,)
GW2
(585,)
GW3
(405,)
GW4
(584,)
GW5
(585,)
GW6
(585,)
GW7
(658,)
GW8
(658,)
GW9
(658,)
GW10
(730,)

In [ ]:
for GW in range(1,gameweek + 1):
  print(f"GW{GW}")
  print(len(data[data["GW"]==GW]["team"].unique()))
  print(data[data["GW"]==GW].drop_duplicates(subset="team")[["team","opponent","last_season_position","mean team Goal scored all","opp mean team Goal scored all"]].reset_index().drop("index",axis=1))#.sort_values("last_season_position"))
  print("\n\n")
  #.sort_values(by="mean team Goal scored all", ascending=False)

GW1
20
              team        opponent  last_season_position  \
0            Spurs       Brentford                     8
1         Brighton           Luton                     6
2         West Ham     Bournemouth                    14
3        Brentford           Spurs                     9
4          Arsenal   Nott'm Forest                     2
5          Man Utd          Wolves                     3
6          Everton          Fulham                    17
7          Chelsea       Liverpool                    12
8    Sheffield Utd  Crystal Palace                    20
9      Bournemouth        West Ham                    15
10           Luton        Brighton                    20
11       Liverpool         Chelsea                     5
12          Fulham         Everton                    10
13   Nott'm Forest         Arsenal                    16
14       Newcastle     Aston Villa                     4
15     Aston Villa       Newcastle                     7
16         Burnley        Man City                    20
17        Man City         Burnley                     1
18          Wolves         Man Utd                    13
19  Crystal Palace   Sheffield Utd                    11

    mean team Goal scored all  opp mean team Goal scored all
0                         2.0                            NaN
1                         NaN                            NaN
2                         NaN                            NaN
3                         NaN                            2.0
4                         NaN                            NaN
5                         NaN                            NaN
6                         NaN                            NaN
7                         NaN                            NaN
8                         NaN                            NaN
9                         NaN                            NaN
10                        NaN                            NaN
11                        NaN                            NaN
12                        NaN                            NaN
13                        NaN                            NaN
14                        NaN                            NaN
15                        NaN                            NaN
16                        NaN                            NaN
17                        NaN                            NaN
18                        NaN                            NaN
19                        NaN                            NaN



GW2
18
              team        opponent  last_season_position  \
0        Newcastle       Liverpool                     4
1         Brighton        West Ham                     6
2          Chelsea           Luton                    12
3         Man City   Sheffield Utd                     1
4          Arsenal          Fulham                     2
5        Brentford  Crystal Palace                     9
6            Spurs     Bournemouth                     8
7      Aston Villa         Burnley                     7
8      Bournemouth           Spurs                    15
9    Nott'm Forest         Man Utd                    16
10         Man Utd   Nott'm Forest                     3
11  Crystal Palace       Brentford                    11
12          Fulham         Arsenal                    10
13        West Ham        Brighton                    14
14       Liverpool       Newcastle                     5
15          Wolves         Everton                    13
16         Everton          Wolves                    17
17   Sheffield Utd        Man City                    20

    mean team Goal scored all  opp mean team Goal scored all
0                         5.0                            1.0
1                         4.0                            1.0
2                         4.0                            NaN
3                         3.0                            0.0
4                         2.0                            1.0
5                         2.0                            1.0
6                         2.0                            1.0
7                         1.0                            NaN
8                         1.0                            2.0
9                         1.0                            1.0
10                        1.0                            1.0
11                        1.0                            2.0
12                        1.0                            2.0
13                        1.0                            4.0
14                        1.0                            5.0
15                        0.0                            0.0
16                        0.0                            0.0
17                        0.0                            3.0



GW3
14
             team        opponent  last_season_position  \
0        Brighton        West Ham                     6
1     Aston Villa         Burnley                     7
2       Brentford  Crystal Palace                     9
3       Newcastle       Liverpool                     4
4         Chelsea           Luton                    12
5   Nott'm Forest         Man Utd                    16
6           Spurs     Bournemouth                     8
7        Man City   Sheffield Utd                     1
8          Wolves   Sheffield Utd                    13
9         Man Utd     Bournemouth                     3
10        Arsenal          Fulham                     2
11    Bournemouth           Spurs                    15
12  Sheffield Utd        Man City                    20
13        Burnley     Aston Villa                    20

    mean team Goal scored all  opp mean team Goal scored all
0                         4.0                            NaN
1                         4.0                            0.0
2                         3.0                            NaN
3                         2.5                            NaN
4                         2.5                            NaN
5                         2.0                            2.0
6                         2.0                            1.0
7                         2.0                            1.0
8                         2.0                            1.0
9                         2.0                            1.0
10                        1.5                            NaN
11                        1.0                            2.0
12                        1.0                            2.0
13                        0.0                            4.0



GW4
19
              team        opponent  last_season_position  \
0         Brighton       Newcastle                     6
1      Aston Villa       Liverpool                     7
2        Liverpool     Aston Villa                     5
3         West Ham           Luton                    14
4          Chelsea   Nott'm Forest                    12
5        Newcastle        Brighton                     4
6    Sheffield Utd         Everton                    20
7            Spurs         Burnley                     8
8         Man City          Fulham                     1
9        Brentford     Bournemouth                     9
10   Nott'm Forest         Chelsea                    16
11         Man Utd         Arsenal                     3
12          Wolves  Crystal Palace                    13
13         Arsenal         Man Utd                     2
14  Crystal Palace         Arsenal                    11
15           Luton         Arsenal                    20
16     Bournemouth       Brentford                    15
17          Fulham        Man City                    10
18         Everton   Sheffield Utd                    17

    mean team Goal scored all  opp mean team Goal scored all
0                    4.000000                       2.500000
1                    3.500000                       3.000000
2                    3.000000                       3.500000
3                    3.000000                       1.666667
4                    2.666667                       2.000000
5                    2.500000                       4.000000
6                    2.500000                       0.000000
7                    2.428571                            NaN
8                    2.000000                       0.500000
9                    2.000000                       0.666667
10                   2.000000                       2.666667
11                   2.000000                       1.666667
12                   2.000000                       1.666667
13                   1.666667                       2.000000
14                   1.666667                       1.666667
15                   1.666667                       1.666667
16                   0.666667                       2.000000
17                   0.500000                       2.000000
18                   0.000000                       2.500000



GW5
19
              team        opponent  last_season_position  \
0         Brighton         Man Utd                     6
1            Spurs   Sheffield Utd                     8
2        Liverpool          Wolves                     5
3         Man City        West Ham                     1
4    Sheffield Utd           Spurs                    20
5         West Ham        Man City                    14
6      Aston Villa  Crystal Palace                     7
7   Crystal Palace     Aston Villa                    11
8        Brentford       Newcastle                     9
9          Arsenal         Everton                     2
10          Wolves       Liverpool                    13
11           Luton          Fulham                    20
12       Newcastle       Brentford                     4
13         Chelsea     Bournemouth                    12
14         Man Utd        Brighton                     3
15   Nott'm Forest         Burnley                    16
16     Bournemouth         Chelsea                    15
17         Everton         Arsenal                    17
18          Fulham           Luton                    10

    mean team Goal scored all  opp mean team Goal scored all
0                    3.666667                       1.750000
1                    3.500000                       3.000000
2                    3.000000                       2.000000
3                    3.000000                       2.500000
4                    3.000000                       3.500000
5                    2.500000                       3.000000
6                    2.333333                       2.000000
7                    2.000000                       2.333333
8                    2.000000                       2.000000
9                    2.000000                       1.000000
10                   2.000000                       3.000000
11                   2.000000                       0.666667
12                   2.000000                       2.000000
13                   2.000000                       1.000000
14                   1.750000                       3.666667
15                   1.666667                            NaN
16                   1.000000                       2.000000
17                   1.000000                       2.000000
18                   0.666667                       2.000000



GW6
19
              team        opponent  last_season_position  \
0         Brighton     Bournemouth                     6
1         Man City   Nott'm Forest                     1
2            Spurs         Arsenal                     8
3        Liverpool        West Ham                     5
4      Aston Villa         Chelsea                     7
5    Sheffield Utd       Newcastle                    20
6         West Ham       Liverpool                    14
7          Arsenal           Spurs                     2
8           Wolves           Luton                    13
9   Crystal Palace          Fulham                    11
10       Newcastle   Sheffield Utd                     4
11       Brentford         Everton                     9
12         Chelsea     Aston Villa                    12
13           Luton          Wolves                    20
14         Man Utd         Burnley                     3
15   Nott'm Forest        Man City                    16
16     Bournemouth        Brighton                    15
17          Fulham  Crystal Palace                    10
18         Everton       Brentford                    17

    mean team Goal scored all  opp mean team Goal scored all
0                    3.500000                       0.800000
1                    3.000000                       1.500000
2                    3.000000                       1.800000
3                    3.000000                       2.000000
4                    2.500000                       1.600000
5                    2.500000                       1.750000
6                    2.000000                       3.000000
7                    1.800000                       3.000000
8                    1.800000                       1.600000
9                    1.800000                       0.750000
10                   1.750000                       2.500000
11                   1.600000                       0.666667
12                   1.600000                       2.500000
13                   1.600000                       1.800000
14                   1.600000                            NaN
15                   1.500000                       3.000000
16                   0.800000                       3.500000
17                   0.750000                       1.800000
18                   0.666667                       1.600000



GW7
20
              team        opponent  last_season_position  \
0         Brighton     Aston Villa                     6
1        Newcastle         Burnley                     4
2        Liverpool           Spurs                     5
3         Man City          Wolves                     1
4            Spurs       Liverpool                     8
5      Aston Villa        Brighton                     7
6    Sheffield Utd        West Ham                    20
7          Burnley       Newcastle                    20
8          Arsenal     Bournemouth                     2
9         West Ham   Sheffield Utd                    14
10          Wolves        Man City                    13
11       Brentford   Nott'm Forest                     9
12  Crystal Palace         Man Utd                    11
13           Luton         Everton                    20
14         Man Utd  Crystal Palace                     3
15         Chelsea          Fulham                    12
16         Everton           Luton                    17
17   Nott'm Forest       Brentford                    16
18     Bournemouth         Arsenal                    15
19          Fulham         Chelsea                    10

    mean team Goal scored all  opp mean team Goal scored all
0                    3.400000                       2.200000
1                    3.000000                       2.000000
2                    3.000000                       2.750000
3                    2.800000                       1.666667
4                    2.750000                       3.000000
5                    2.200000                       3.400000
6                    2.000000                       1.750000
7                    2.000000                       3.000000
8                    1.833333                       0.833333
9                    1.750000                       2.000000
10                   1.666667                       2.800000
11                   1.500000                       1.200000
12                   1.500000                       1.500000
13                   1.500000                       1.250000
14                   1.500000                       1.500000
15                   1.333333                       0.600000
16                   1.250000                       1.500000
17                   1.200000                       1.500000
18                   0.833333                       1.833333
19                   0.600000                       1.333333



GW8
20
              team        opponent  last_season_position  \
0         Brighton       Liverpool                     6
1        Newcastle        West Ham                     4
2      Aston Villa          Wolves                     7
3            Spurs           Luton                     8
4        Liverpool        Brighton                     5
5         Man City         Arsenal                     1
6          Arsenal        Man City                     2
7          Burnley         Chelsea                    20
8         West Ham       Newcastle                    14
9           Wolves     Aston Villa                    13
10   Sheffield Utd          Fulham                    20
11           Luton           Spurs                    20
12       Brentford         Man Utd                     9
13         Chelsea         Burnley                    12
14  Crystal Palace   Nott'm Forest                    11
15         Man Utd       Brentford                     3
16         Everton     Bournemouth                    17
17   Nott'm Forest  Crystal Palace                    16
18     Bournemouth         Everton                    15
19          Fulham   Sheffield Utd                    10

    mean team Goal scored all  opp mean team Goal scored all
0                    3.000000                       2.600000
1                    2.833333                       1.800000
2                    2.833333                       1.714286
3                    2.600000                       1.571429
4                    2.600000                       3.000000
5                    2.500000                       2.166667
6                    2.166667                       2.500000
7                    2.000000                       1.428571
8                    1.800000                       2.833333
9                    1.714286                       2.833333
10                   1.666667                       0.500000
11                   1.571429                       2.600000
12                   1.428571                       1.285714
13                   1.428571                       2.000000
14                   1.428571                       1.166667
15                   1.285714                       1.428571
16                   1.200000                       0.714286
17                   1.166667                       1.428571
18                   0.714286                       1.200000
19                   0.500000                       1.666667



GW9
20
              team        opponent  last_season_position  \
0         Brighton        Man City                     6
1        Newcastle  Crystal Palace                     4
2      Aston Villa        West Ham                     7
3        Liverpool         Everton                     5
4            Spurs          Fulham                     8
5         Man City        Brighton                     1
6          Arsenal         Chelsea                     2
7         West Ham     Aston Villa                    14
8          Chelsea         Arsenal                    12
9          Burnley       Brentford                    20
10          Wolves     Bournemouth                    13
11   Sheffield Utd         Man Utd                    20
12         Everton       Liverpool                    17
13           Luton   Nott'm Forest                    20
14       Brentford         Burnley                     9
15         Man Utd   Sheffield Utd                     3
16  Crystal Palace       Newcastle                    11
17   Nott'm Forest           Luton                    16
18          Fulham           Spurs                    10
19     Bournemouth          Wolves                    15

    mean team Goal scored all  opp mean team Goal scored all
0                    2.857143                       2.142857

In [ ]:
data[pd.isna(data["opp mean team Goal scored all"])]["GW"].value_counts()

1    582
3    174
2     72
5     44
4     34
6     34
Name: GW, dtype: int64

In [ ]:
data[pd.isna(data["opp mean team Goal scored all"])]. shape

(940, 122)

In [ ]:
data[pd.isna(data["opp mean team Goal scored all"])]["GW"].value_counts()

1    582
3    174
2     72
5     44
4     34
6     34
Name: GW, dtype: int64

In [ ]:
data_gw[pd.isna(data_gw["opp mean team Goal scored all"])]["opponent"].value_counts()

Series([], Name: opponent, dtype: int64)

In [ ]:
data_gw[data_gw["opponent"]=="Crystal Palace"][["name","team"]]

                              name   team
107               Micky van de Ven  Spurs
108                  Dane Scarlett  Spurs
109                    Alejo Véliz  Spurs
110                Pape Matar Sarr  Spurs
111                    Hugo Lloris  Spurs
113         Tanguy Ndombélé Alvaro  Spurs
116                  Manor Solomon  Spurs
117                Japhet Tanganga  Spurs
118                 James Maddison  Spurs
126               Davinson Sánchez  Spurs
128               Dejan Kulusevski  Spurs
130                 Destiny Udogie  Spurs
132                Cristian Romero  Spurs
133              Guglielmo Vicario  Spurs
134                      Joe Rodon  Spurs
135                    Pedro Porro  Spurs
138               Giovani Lo Celso  Spurs
140         Richarlison de Andrade  Spurs
142                 Ryan Sessegnon  Spurs
145                   Ivan Perišić  Spurs
147                   Oliver Skipp  Spurs
149                    Djed Spence  Spurs
150                  Son Heung-min  Spurs
155                 Alfie Whiteman  Spurs
157  Emerson Leite de Souza Junior  Spurs
158                 Fraser Forster  Spurs
159                     Harry Kane  Spurs
160          Bryan Gil Salvatierra  Spurs
161                     Ben Davies  Spurs
162              Rodrigo Bentancur  Spurs
163                  Yves Bissouma  Spurs
164                      Eric Dier  Spurs
165          Pierre-Emile Højbjerg  Spurs
166                 Brandon Austin  Spurs
231                Brennan Johnson  Spurs
670                Ashley Phillips  Spurs
693                   Jamie Donley  Spurs